### ISSUE TITLE
BNG Parser not running in 2.1.0 Mac version on some machines

### ISSUE THREAD

**Issue by jrfaeder** [RuleWorld/rulebender#178]
![image](https://cloud.githubusercontent.com/assets/8277248/11981461/da0e3126-a970-11e5-82c9-c4e71ea5b984.png)
This error arises upon saving a file with changes on a Mac running OS X 10.10.5.
Contact map also does not display.
Simulations and output seem to work fine.
The only known machine that gives this error is Jim's desktop (Mac mini) in BST3.

**Comment by rhclark** [comment]
I may need to get on Jim's Macintosh in order to reproduce this.  Using his workspace, I tried to find some models for which no contact map  was generated on my Macintosh, and I couldn't find any.  It occurred to me that the parser .jar file is not the only .jar file that gets rolled into the build process, and fixing this bug might involve analysing all of the .jar files to see which one is out of synch with his runtime environment.

**Comment by rhclark** [comment]
I also did a search for "Save Failed" in the RuleBender source code, and I couldn't find that string.  I also did a search for the number "51", and the search did not turn up that error message. So since we don't seem to issue that dialogue box ourselves,  I'm no longer considering the possibility that it's just the wrong message.

**Comment by rhclark** [comment]
Fixed !!  It turns out that the best work around for this is to install the most recent  Java JDK from Oracle.  Until recently the Apple Macintosh was shipped with Java 1.6 preinstalled.   This Runtime Environment can be upgraded fairly easily with a plug-in-play download of the RTE for browsers.  But RuleBender can't benefit from this.  To give RuleBender what it needs, you will need to get the Java JDK installation package from  java.com  and install it.  It'll be installed in a different location from the browser RTE.
